#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

[options]
  # GUI
  colorscheme = "onedark"
  colorscheme_bg = "dark"
  enable_guicolors = true
  statusline_separator = "nil"
  statusline_iseparator = "nil"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = false
  relativenumber = false
  # checkers
  enable_neomake = false
  enable_ale = true
  lint_on_the_fly = true
  # boot functions 
  bootstrap_before = 'boot#before'

# GUI 
[[layers]]
  name = 'colorscheme'

# plugins
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = "checkers"

[[layers]]
  name = "git"

[[layers]]
  name = "VersionControl"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "denite"

[[layers]]
  name = "lang#c"
  clang_executable = "/usr/bin/clang"
  libclang_path = "/usr/lib/libclang.so"

[[custom_plugins]]
  repo = "Olical/conjure"

  
